# Generated by Django 4.0.5 on 2022-06-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizalo', '0002_alter_monto_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=300)),
                ('Monto', models.IntegerField()),
                ('Cuenta', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Descripcion',
        ),
        migrations.DeleteModel(
            name='Monto',
        ),
    ]
