# Generated by Django 4.0.5 on 2022-06-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizalo', '0003_transaccion_delete_cuenta_delete_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='Cuenta',
            field=models.IntegerField(choices=[[0, 'Debito Banco Estado'], [1, 'Visa'], [2, 'Mach'], [3, 'Efectivo']]),
        ),
    ]
