# Generated by Django 4.0.5 on 2022-06-29 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizalo', '0003_transaccion_delete_cuenta_delete_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='Cuenta',
            field=models.IntegerField(choices=[[0, 'Debito Banco Estado'], [1, 'Visa'], [2, 'Mach'], [3, 'Efectivo']]),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizalo.code'),
        ),
    ]
