# Generated by Django 4.0.5 on 2022-07-01 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Descripcion', models.CharField(max_length=150)),
                ('Monto', models.IntegerField()),
                ('Cuenta', models.IntegerField(choices=[[0, 'Debito'], [1, 'Visa'], [2, 'Mach'], [3, 'Efectivo']])),
                ('Codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizaloo.codigo')),
            ],
        ),
    ]
