# Generated by Django 4.0.5 on 2022-07-01 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizaloo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='Codigo',
        ),
        migrations.DeleteModel(
            name='Codigo',
        ),
    ]
