# Generated by Django 4.0.5 on 2022-07-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizaloo', '0003_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='correo',
            new_name='Correo',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='mensaje',
            new_name='Mensaje',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='tipo_consulta',
            new_name='Tipo_consulta',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
    ]
