# Generated by Django 4.0.5 on 2022-07-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizaloo', '0004_rename_correo_contacto_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
